# Generated by Django 3.2 on 2021-05-05 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockitem',
            old_name='item_description',
            new_name='identification_marker',
        ),
        migrations.RemoveField(
            model_name='stockitem',
            name='stock_price',
        ),
    ]
