# Generated by Django 3.2 on 2021-05-05 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_auto_20210505_2116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockitem',
            name='slug',
        ),
    ]
