# Generated by Django 3.2 on 2021-05-14 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0003_remove_stockitem_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockitem',
            name='quantity',
        ),
        migrations.CreateModel(
            name='StockQuantities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stock_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.stockitem')),
            ],
        ),
    ]
